spring:
  datasource:
    url: jdbc:mysql://mysql-container/eongaz?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

repository-type: JPA
create-seed: TRUE