spring:
  datasource:
    url: jdbc:mysql://localhost:3306/academy?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

repository-type: JPA